// Regenerates src/data/words.json from the compact lists below.
// Run: node scripts/buildWords.mjs
import { writeFileSync } from "node:fs";

const lists = {
  breakfast: `PANCAKE WAFFLE OMELET BACON CEREAL TOAST MUFFIN BAGEL OATMEAL GRANOLA YOGURT SAUSAGE CROISSANT BISCUIT SYRUP BUTTER JAM HASH_BROWN FRITTATA CREPE DONUT SCONE PASTRY MILK JUICE COFFEE BLUEBERRY BANANA FRENCH_TOAST PORRIDGE CINNAMON CREAM_CHEESE EGGS HAM GRITS DANISH STRAWBERRY HONEY SMOOTHIE QUICHE`,
  sports: `SOCCER TENNIS HOCKEY BASEBALL BASKETBALL VOLLEYBALL GOLF RUGBY CRICKET BOXING SWIMMING DIVING ROWING SAILING SURFING SKIING SNOWBOARD CURLING FENCING ARCHERY BADMINTON LACROSSE HANDBALL GYMNASTICS WRESTLING CYCLING MARATHON TRIATHLON BOWLING SKATEBOARD SOFTBALL POLO KAYAKING CLIMBING JUDO KARATE DODGEBALL PICKLEBALL SQUASH FOOTBALL`,
  space: `PLANET GALAXY COMET ASTEROID ROCKET ORBIT METEOR NEBULA SATELLITE TELESCOPE ASTRONAUT MOON SUN STAR MERCURY VENUS EARTH MARS JUPITER SATURN URANUS NEPTUNE ECLIPSE UNIVERSE GRAVITY COSMOS CRATER SHUTTLE CAPSULE STARDUST SUPERNOVA QUASAR PULSAR CONSTELLATION LAUNCH LANDER ROVER SOLAR_SYSTEM BLACK_HOLE MILKY_WAY AURORA`,
  clothing: `JACKET SWEATER SCARF MITTENS SOCKS SNEAKERS BOOTS SANDALS HOODIE JEANS SHORTS SKIRT DRESS SHIRT BLOUSE VEST COAT RAINCOAT GLOVES HAT BEANIE CAP APRON OVERALLS PAJAMAS SLIPPERS LEGGINGS TUXEDO CARDIGAN POLO TIGHTS BELT SUSPENDERS BANDANA PONCHO UNIFORM HELMET KNEE_PADS T-SHIRT SWEATPANTS SUNHAT`,
  animals: `ELEPHANT GIRAFFE PENGUIN DOLPHIN KANGAROO PANDA TIGER LION ZEBRA MONKEY GORILLA HIPPO RHINO CHEETAH LEOPARD WOLF FOX RABBIT SQUIRREL BEAVER OTTER BADGER HEDGEHOG PORCUPINE RACCOON MOOSE BISON CAMEL LLAMA ALPACA KOALA PLATYPUS FLAMINGO PARROT TOUCAN OWL EAGLE FALCON TURTLE LIZARD IGUANA`,
  ocean: `OCTOPUS JELLYFISH SEAHORSE STARFISH LOBSTER CRAB SHRIMP WHALE SHARK DOLPHIN TURTLE CORAL REEF ANEMONE CLAMS OYSTER SEAWEED KELP TIDE WAVE CURRENT HARBOR LIGHTHOUSE ANCHOR SAILBOAT SUBMARINE SNORKEL SEAGULL PELICAN WALRUS SEAL MANATEE BARNACLE SQUID EEL STINGRAY PUFFERFISH ANGLERFISH CLOWNFISH TRENCH ISLAND`,
  music: `GUITAR PIANO VIOLIN DRUMS TRUMPET FLUTE CLARINET SAXOPHONE CELLO HARP BANJO UKULELE TROMBONE TUBA OBOE BASSOON ACCORDION HARMONICA XYLOPHONE TAMBOURINE MELODY RHYTHM HARMONY CHORUS TEMPO ENCORE CONCERT ORCHESTRA CHOIR OPERA SYMPHONY LULLABY BALLAD ANTHEM SONG LYRICS SOLO DUET BAND RECORD PLAYLIST`,
  nature: `FOREST MOUNTAIN RIVER WATERFALL MEADOW CANYON VALLEY DESERT GLACIER VOLCANO ISLAND LAKE POND STREAM BREEZE THUNDER LIGHTNING RAINBOW BLIZZARD SUNSET SUNRISE SEASON AUTUMN WINTER SPRING SUMMER BLOSSOM PETAL BOULDER PEBBLE CAVERN SWAMP TUNDRA PRAIRIE JUNGLE OASIS CLOUD FOG DEW FROST`,
  school: `PENCIL ERASER NOTEBOOK BACKPACK LOCKER TEACHER STUDENT CLASSROOM LIBRARY HOMEWORK RECESS LUNCHBOX BLACKBOARD CHALK MARKER RULER CALCULATOR SCISSORS GLUE CRAYON TEXTBOOK DICTIONARY ATLAS GLOBE MICROSCOPE SCIENCE HISTORY GEOGRAPHY ALGEBRA GEOMETRY SPELLING READING WRITING ART GYM PRINCIPAL CAFETERIA DIPLOMA GRADUATION FIELD_TRIP`,
  travel: `PASSPORT SUITCASE AIRPORT TICKET LUGGAGE HOTEL ITINERARY TOURIST JOURNEY ADVENTURE VACATION CRUISE TRAIN STATION SUBWAY TAXI BUS FERRY AIRPLANE PILOT MAP COMPASS CAMPING TENT HOSTEL SOUVENIR POSTCARD BEACH RESORT TRAILHEAD HIKING BACKPACKER ROAD_TRIP HIGHWAY BRIDGE TUNNEL LANDMARK MUSEUM CASTLE MONUMENT CUSTOMS VISA`,
  jobs: `BAKER CARPENTER PLUMBER ELECTRICIAN FIREFIGHTER DOCTOR NURSE DENTIST PILOT ARCHITECT ENGINEER SCIENTIST TEACHER LIBRARIAN FARMER FISHERMAN CHEF WAITER BARISTA MECHANIC PAINTER SCULPTOR PHOTOGRAPHER JOURNALIST DESIGNER PROGRAMMER ACCOUNTANT LAWYER JUDGE MAIL_CARRIER GARDENER BUTCHER TAILOR COACH LIFEGUARD ASTRONOMER VETERINARIAN MUSICIAN ACTOR DANCER`,
  food: `PIZZA SPAGHETTI HAMBURGER SANDWICH BURRITO TACO SUSHI NOODLES SALAD SOUP CHEESE BROCCOLI CARROT POTATO TOMATO CUCUMBER PEPPER ONION GARLIC MUSHROOM SPINACH LETTUCE CORN PEAS APPLE ORANGE GRAPES WATERMELON PINEAPPLE MANGO PEACH CHERRY LEMON COOKIE BROWNIE CUPCAKE PRETZEL POPCORN ICE_CREAM LASAGNA DUMPLING PAELLA`,
  games: `CHECKERS CHESS DOMINOES MONOPOLY SCRABBLE PUZZLE CROSSWORD JIGSAW CHARADES HIDE_AND_SEEK TAG HOPSCOTCH MARBLES JACKS YOYO KITE FRISBEE TRAMPOLINE SEESAW SANDBOX SWING SLIDE PLAYGROUND DICE CARDS POKER BINGO TRIVIA RIDDLE ARCADE PINBALL JOYSTICK CONTROLLER AVATAR LEVEL BOSS_FIGHT SCOREBOARD TREASURE MAZE`,
  phrases: `DON'T_STOP ROLLER_RINK SPIN_AROUND SKATE_PARK GOOD_VIBES PIECE_OF_CAKE BREAK_A_LEG HOT_POTATO SUNNY_SIDE_UP TOP_OF_THE_MORNING FULL_SPEED_AHEAD ROLL_WITH_IT SMOOTH_SAILING COOL_AS_A_CUCUMBER BEST_FOOT_FORWARD ON_A_ROLL LIFE_OF_THE_PARTY HOME_RUN HIGH_FIVE SWEET_DREAMS LUCKY_CHARM FAIR_AND_SQUARE ONCE_IN_A_BLUE_MOON SKATE_AWAY TWIST_AND_SHOUT`,
};

const entries = [];
const seen = new Set();
for (const [category, raw] of Object.entries(lists)) {
  for (const token of raw.split(/\s+/).filter(Boolean)) {
    const text = token.replaceAll("_", " ");
    if (!/^[A-Z][A-Z' -]*$/.test(text)) throw new Error(`Invalid word: ${text}`);
    if (seen.has(text)) continue;
    seen.add(text);
    entries.push({ text, category });
  }
}

const json = "[\n" + entries.map((e) => "  " + JSON.stringify(e)).join(",\n") + "\n]\n";
writeFileSync(new URL("../src/data/words.json", import.meta.url), json);
console.log(entries.length, "words");

